packages:
  - apps/*
  - packages/*
  - tooling/*
  - examples/*

catalog:
  typescript: ^5.9.3
  react: ^19.2.4
  react-dom: ^19.2.4
  next: ^16.1.6
  tsdown: ^0.18.1
  vite: ^7.3.1

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - lefthook
  - sharp
  - unrs-resolver
