name: CLI Issue
description: Report a bug or gap in the twist-toast CLI package.
title: "[cli] "
labels:
  - cli
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken or missing?
      placeholder: Short description of the issue.
    validations:
      required: true

  - type: dropdown
    id: run_mode
    attributes:
      label: How did you run the CLI?
      options:
        - npx twist-toast@latest
        - pnpm dlx twist-toast@latest
        - twist-toast (global install)
    validations:
      required: true

  - type: input
    id: command
    attributes:
      label: Command used
      placeholder: add toast-root
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run command...
        2. Select option...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected result
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual result and logs
      description: Paste the full terminal error/log output.
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: Environment
      placeholder: |
        OS:
        Node:
        pnpm/npm:
        CLI package version:
    validations:
      required: true

